{
 "title": "MQTT Broker Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connect Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_connect_received" }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_pingreq_received" }
   ]
  },
  {
   "title": "Publish Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_publish_received" }
   ]
  },
  {
   "title": "Subscribe Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_subscribe_received" }
   ]
  }
 ]
}