version: '3'
services:
  mqtt-broker:
    image: vernemq/vernemq
    restart: always
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # allow anonymous users
