version: '3'
services:

  mqtt-broker:
    image: vernemq/vernemq
    restart: always
    ports:
      - "1883:1883"
      - "8888:8888"
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # allow anonymous users

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    command: --config.file=/etc/prometheus/prometheus.yml

#  grafana:
#    image: grafana/grafana
#    ports:
#      - "80:3000"
#    volumes:
#      - ../grafana/:/var/lib/grafana # see https://stackoverflow.com/questions/34031397/running-docker-on-ubuntu-mounted-host-volume-is-not-writable-from-container

  identity-node:
    image: identity-node:v0
    ports:
      - "3000:3000"
    volumes:
      - ../identity-node:/src
    restart: always
    environment:
      IDENTITY_DEBUG: "false"
      IDENTITY_HTTP_SERVER_PORT: 3000
      IDENTITY_MQTT_BROKER_HOST: mqtt-broker
      IDENTITY_MQTT_BROKER_PORT: 1883
      IDENTITY_MQTT_PRODUCER_ID: identity-0
      IDENTITY_MQTT_WELCOME_TOPIC: identity/welcome
    working_dir: /src
    command: bash -c "go mod download && cd ./src && modd && go run"

  feed-producer:
      image: feed-producer:v0
      volumes:
        - ../feed-producer:/app
      restart: always
      environment:
        PRODUCER_WEATHER_APIKEY: 79c9118b24b5b9dc61998d484842f0dc
        PRODUCER_WEATHER_CITIES: catania|acireale|misterbianco|paternò
#        PRODUCER_WEATHER_STATES: it
        PRODUCER_WEATHER_TIME: 3600 # seconds
#        WEATHER_URL: https://api.openweathermap.org/data/2.5/forecast

  feed-provider:
      image: feed-provider:v0
      volumes:
        - ../feed-provider:/app
      restart: always
      environment:
        PROVIDER_HTTP_SERVER_PORT: 3030
        PROVIDER_MQTT_BROKER_HOST: mqtt-broker
        PROVIDER_MQTT_BROKER_PORT: 1883
        PROVIDER_MQTT_PRODUCER_ID: provider-0
        PROVIDER_MQTT_WELCOME_TOPIC: provider/welcome

  redis:
      container_name: redis
      image: redis:5-alpine
      ports:
        - "6379:6379"
