version: '3'
services:
  mqtt-broker:
    image: vernemq/vernemq
    restart: always
    ports:
      - "1883:1883"
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on # allow anonymous users
  identity-node:
    image: identity-node:v0
    ports:
      - "3000:3000"
    volumes:
      - ../identity-node:/src
    restart: always
    environment:
      IDENTITY_DEBUG: "true"
      IDENTITY_HTTP_SERVER_PORT: 3000
      IDENTITY_MQTT_BROKER_HOST: mqtt-broker
      IDENTITY_MQTT_BROKER_PORT: 1883
      IDENTITY_MQTT_PRODUCER_ID: identity-0
      IDENTITY_MQTT_WELCOME_TOPIC: identity/welcome
    working_dir: /src
    #command: bash -c "go mod download && modd && go run ." # see https://blog.golang.org/using-go-modules
    command: bash -c "go mod download && cd ./src && modd && go run"
