# voglio la feature di live reload per il development
# ergo: non voglio ribuildare l'immagine per vedere modifiche fatte al codebase
# see https://levelup.gitconnected.com/how-to-live-reload-code-for-golang-and-docker-without-third-parties-ee90721ef641

FROM golang:alpine

WORKDIR /src

RUN apk add --no-cache alpine-sdk bash git && env GO111MODULE=on go get github.com/cortesi/modd/cmd/modd

# CMD ["go", "run", "main.go"]
